version: "3.7"
services:
  postgres96-server:
    build: .
    image: carlosamorim/postgres96
    container_name: postgres96-server
    #network_mode: net_sps
    network_mode: bridge
    ports:
      - "5433:5432"
    restart: always
    environment:
      - PATH=$PATH:/var/lib/postgresql/bin
      - PGDATA=/var/lib/postgresql/data
      - PGPORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /home/carlos/pgdata/data96:/var/lib/postgresql/data
    entrypoint: ["/var/lib/postgresql/entry-point.sh"]
    command: -p 5433
